# Generated by Django 5.2.4 on 2025-07-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step1', models.JSONField()),
                ('step2', models.JSONField()),
                ('step3', models.JSONField()),
                ('step4', models.JSONField()),
                ('step5', models.JSONField()),
                ('step6', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
