# Generated by Django 5.2.4 on 2025-08-05 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyresponse',
            old_name='step1',
            new_name='answers',
        ),
        migrations.RenameField(
            model_name='surveyresponse',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='step2',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='step3',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='step4',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='step5',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='step6',
        ),
    ]
